//! What every viewer says about duscape itself: its name and version, who holds its copyright,
//! its licence, the licences of the work it contains, and where to find it. One source, so the
//! terminal's `--version` and `--licenses`, and each window's About, say the same thing.
//!
//! The licence texts are the files the releases ship beside the binaries, embedded:
//! `LICENSE`, and `THIRD-PARTY-LICENSES.txt` (generated by `make third-party`, checked in CI),
//! every crate compiled into a duscape binary with its licence, then Rust's standard library,
//! musl and jemalloc.

/// The program's name.
pub const NAME: &str = "duscape";

/// The version, the workspace's: every crate of it carries the same.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");

/// What it is, in a line.
pub const SUMMARY: &str = "Where your disk space went: a treemap that fills in while it scans.";

/// The project's home.
pub const HOMEPAGE: &str = env!("CARGO_PKG_HOMEPAGE");

/// Where to report a problem.
pub const ISSUES: &str = concat!(env!("CARGO_PKG_HOMEPAGE"), "/issues");

/// duscape's licence, `LICENSE` as shipped.
pub const LICENSE: &str = include_str!("../../LICENSE");

/// The licences of everything else a duscape binary contains, `THIRD-PARTY-LICENSES.txt`.
pub const THIRD_PARTY_LICENSES: &str = include_str!("../../THIRD-PARTY-LICENSES.txt");

/// The licence's name, as `Cargo.toml` gives it.
pub const LICENSE_NAME: &str = env!("CARGO_PKG_LICENSE");

/// The copyright lines of `LICENSE`, in its order: diskonaut's author's, then the fork's.
pub fn copyrights() -> impl Iterator<Item = &'static str> {
    LICENSE.lines().filter(|line| line.starts_with("Copyright"))
}

/// What an About box says, as lines: the name and version, what it is, the copyrights, the
/// licence, and where to find it. A viewer lays them out as it can; a blank line separates the
/// parts.
#[must_use]
pub fn lines() -> Vec<String> {
    let mut lines = vec![
        format!("{NAME} {VERSION}"),
        SUMMARY.to_string(),
        String::new(),
    ];
    lines.extend(copyrights().map(str::to_string));
    lines.push(format!(
        "{LICENSE_NAME} licence. It contains the work of others, under their own licences."
    ));
    lines.push(String::new());
    lines.push(HOMEPAGE.to_string());
    lines.push(format!("Report a problem: {ISSUES}"));
    lines
}

/// The licences in full, for `--licenses` and a window's "Licences" view: duscape's, then the
/// third parties'.
#[must_use]
pub fn licenses() -> String {
    format!("{LICENSE}\n\n{THIRD_PARTY_LICENSES}")
}

/// The licences written to a text file in the temporary folder, for a window to open with the
/// system's text viewer; its path. Written afresh each time: the folder is anyone's to clean.
///
/// # Errors
/// When the file cannot be written.
pub fn licenses_file() -> ::std::io::Result<::std::path::PathBuf> {
    let path = ::std::env::temp_dir().join(format!("{NAME}-{VERSION}-licences.txt"));
    ::std::fs::write(&path, licenses())?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_copyrights_are_licenses_both_lines() {
        let lines: Vec<&str> = copyrights().collect();
        assert_eq!(lines.len(), 2, "{lines:?}");
        assert!(lines[0].contains("Aram Drevekenin"));
        assert!(lines[1].contains("Ang Chin Han and duscape contributors"));
    }

    #[test]
    fn the_about_lines_name_the_version_licence_and_home() {
        let lines = lines();
        assert_eq!(lines[0], format!("duscape {VERSION}"));
        assert!(lines.iter().any(|line| line.starts_with("MIT licence")));
        assert!(lines.iter().any(|line| line.ends_with("/issues")));
        assert!(lines.contains(&HOMEPAGE.to_string()));
    }

    #[test]
    fn the_licences_hold_duscapes_and_every_third_partys() {
        let text = licenses();
        assert!(text.starts_with("The MIT License"));
        // Third parties of each platform, and what Cargo does not list.
        for name in [
            "  ratatui ",
            "  x11rb ",
            "  windows-sys ",
            "  objc2 ",
            "musl libc",
            "jemalloc",
        ] {
            assert!(text.contains(name), "{name} missing");
        }
        // The workspace's own crates are duscape's, under LICENSE: not listed as third parties.
        assert!(!THIRD_PARTY_LICENSES.contains("\n  libduscape "));
    }
}
