name: Test and coverage

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Build cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Run tests (default features)
        run: cargo test --workspace --verbose
      - name: Run tests (--all-features)
        run: cargo test --workspace --all-features --verbose
      - name: Run tests (--no-default-features)
        run: cargo test --workspace --no-default-features --verbose
      - name: Generate coverage report (libdiskonaut)
        run: |
          cargo llvm-cov --all-features -p libdiskonaut --lcov --output-path lcov-libdiskonaut.info
      - name: Generate coverage report (diskonaut)
        run: |
          cargo llvm-cov --all-features -p diskonaut-angch --lcov --output-path lcov-diskonaut.info
      - name: Upload libdiskonaut coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./lcov-libdiskonaut.info
          flags: libdiskonaut
          name: libdiskonaut
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload diskonaut coverage to Codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./lcov-diskonaut.info
          flags: diskonaut
          name: diskonaut
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
